### ISSUE TITLE
Update documentation on github.io/Add documentation to docs.rs

### ISSUE THREAD

**Issue by Deedasmi** [AndyBarron/preferences-rs#13]
https://andybarron.github.io/docs/preferences-rs/preferences/index.html

Is out of date and does not include new changes to APP_INFO. As this was an API change, more than a little bit of time was wasted until digging into the library to figure out what was wrong.

Additionally, having docs on https://docs.rs/preferences-rs would be nice so crates.io can find the documentation.

**Comment by andybarron** [comment]
Oh crap, thanks for the heads up. I had already updated the crates.io page
to use docs.rs, but I put in the wrong link, and I forgot to update the
link elsewhere - I will change this ASAP, sorry!

The correct link is https://docs.rs/preferences (and it should update
automatically with each release)

**Comment by Deedasmi** [comment]
Thanks!

**Comment by Deedasmi** [comment]
https://docs.rs/crate/preferences/0.7.2

One more spot for you to update it!

**Comment by andybarron** [comment]
That page just mirrors the contents of `README.md`, which is up-to-date. Unfortunately, docs.rs doesn't sync instantly after `cargo publish`. It should be fixed soon (at the link https://docs.rs/crate/preferences, which is version-independent).

**Comment by andybarron** [comment]
The [docs.rs page has auto-updated](https://docs.rs/crate/preferences), and now the self-hosted page redirects to docs.rs: https://andybarron.github.io/preferences-rs
