### ISSUE TITLE
Migrate serialization to serde

### ISSUE THREAD

**Issue by jmacdonald** [AndyBarron/preferences-rs#15]
Now that [Rust 1.15 has been released](https://blog.rust-lang.org/2017/02/02/Rust-1.15.html) and custom derive functionality has stabilized, `preferences` can use `serde`, rather than `rustc-serialize`.

**Comment by andybarron** [comment]
🎉 🎉 🎉  Thanks for pointing this out, I missed the 1.15 announcement! Updating now :D

**Comment by jmacdonald** [comment]
👏 Fantastic, thanks for putting this together so quickly! 😄
