### ISSUE TITLE
Update to serde 1.0

### ISSUE THREAD

**Issue by Boscop** [AndyBarron/preferences-rs#20]
Update to serde and serde_json v1.0, please :)

**Comment by Boscop** [comment]
I can't use this crate for my types which are using `#[derive(Serialize, Deserialize)]` from serde 1.0.
I have to use serde 1.0 because of tarpc, diesel etc.

Can you **please** update this crate to serde 1.0? :)

**Comment by SebastianJL** [comment]
I see that this update has been done about 10 months ago. Could you publish to crates.io?
Asking for a friend :)

**Comment by astraw** [comment]
I just pushed my fork with serde 1 to https://github.com/astraw/preferences-serde1 to https://crates.io/crates/preferences-serde1
