### ISSUE TITLE
Use platform-specific dependencies when Rust 1.8.0 becomes stable

### ISSUE THREAD

**Issue by andybarron** [AndyBarron/preferences-rs#3]
Put all Windows-specific dependencies under `[target.'cfg(windows)'.dependencies]`. (This syntax does not exists in the current stable version of Rust, 1.7.0.)

**Comment by critiqjo** [comment]
Gentle reminder! :smile:

**Comment by andybarron** [comment]
Factored platform-specific dependencies out into [app_dirs](https://github.com/AndyBarron/app-dirs-rs), so this isn't necessary any more!
