### ISSUE TITLE
Add `Preferences::{save_to_<?>, load_from_<?>}`

### ISSUE THREAD

**Issue by andybarron** [AndyBarron/preferences-rs#5]
Was going to use `File`, but maybe `Read`/`Write` would be better; hmm.

**Comment by gyscos** [comment]
This would allow to use compression?

**Comment by andybarron** [comment]
No, this would use the default encoding/decoding. But #6 would definitely allow for compression - just get the file handle/path and do the I/O yourself!

**Comment by gyscos** [comment]
(I meant, if the `Write` given is actually a compressor on top of a `File`, I guess it would allow this?)

**Comment by andybarron** [comment]
Oh, yeah! Duh. Yes, that would work, and will be added soon!
